### ISSUE TITLE
Advice on de-duplicating collection methods?

### ISSUE THREAD

**Issue by idan** [jmorrell/backbone-filtered-collection#2]
I have logic that applies to the collection in aggregate — for example, getting min/max extents for various properties, or calculating durations.

Sometimes I need to run it on the full collection, but often I need the exact same logic for the filtered collection. Right now, I'm finding myself writing two copies of the same method, one for the collection, and one for the filtered collection.

Any suggestion on how to do that in a cleaner fashion?

**Comment by jmorrell** [comment]
Why doesn't one function work for both the original collection and the filtered collection? They should have the same interface / methods available. Got an example?

**Comment by filipegiusti** [comment]
I would like to do something like

``` coffeescript
class Items extends Backbone.Collection
  totalPoints: ->
    @reduce( (totalPoints, item) ->
      totalPoints + item.get('points')
    , 0

items = new Items([])
enabled_items = new FilteredCollection(items)
enabled_items.totalPoints()
```

but the `totalPoints()` method doesn't exists in the filtered collection. I don't see an easy way for FilteredCollection do that, but it would be cool if it could.

**Comment by jmorrell** [comment]
You might be able to create a new class that extends the filtered collection with the additional methods. I'm not entirely sure this will work without trying it, and I'm not sure how coffeescript expands its class syntax so this might not work at all.

``` coffeescript
class MyFilteredItems extends FilteredCollection
  totalPoints: ->
    @reduce( (totalPoints, item) ->
      totalPoints + item.get('points')
    , 0
```

Alternatively, you could try `Items.totalPoints.call(enabled_items);` to call it with the filtered collection as the context, though that's a bit hacky.

I originally thought about allowing custom methods on the filtered collection, but decided against it in the end because it added a lot of complexity.

Yet another alternative is to not make `totalPoints` a method, rather a function that accepts a collection, which would work no matter which is passed in.

``` js
function totalPoints(coll) {
  return sumArray(coll.pluck('points'));
}
```

**Comment by filipegiusti** [comment]
I ended up doing

``` coffee
class Items extends Backbone.Collection
  totalPoints: ->
    @reduce( (totalPoints, item) ->
      totalPoints + item.get('points')
    , 0

class ItemFilteredCollection extends FilteredCollection
  totalPoints: Items::.totalPoints

items = new Items([])
enabled_items = new ItemFilteredCollection(items)
enabled_items.totalPoints()
```

not the most elegant solution but good enough for now.

I'm curious to see if other people have this same use case and how they solved.
